// /api/_curriculum.js
// -------------------------------------------------------------
// The curriculum map for Buildable's Learning Mode (Session 8A).
// One place that says WHAT to practice at each grade and subject, so the weekly
// question factory (api/generate-question-bank.js) makes a balanced, standards-
// shaped mix, and generate-quiz can tag questions with a real skill.
//
// Shape: CURRICULUM[grade][subject] = [skill, skill, ...]
//   grade:   'k','1','2','3','4','5','6'
//   subject: 'math' | 'geometry' | 'spelling' | 'reading'
//   skill:   a short, stable tag (kebab-case). These tags match the ones the
//            quiz payloads carry, so the parent dashboard can report by skill.
//
// Keep it plain data. No emojis anywhere (product rule).
// -------------------------------------------------------------

export const GRADES = ["k", "1", "2", "3", "4", "5", "6"];
export const SUBJECTS = ["math", "geometry", "spelling", "reading"];

// quizType mirrors subject one-to-one today, but keep the mapping explicit so a
// subject could point at a different generator later without touching callers.
export const SUBJECT_TO_QUIZTYPE = {
  math: "math",
  geometry: "geometry",
  spelling: "spelling",
  reading: "reading",
};

export const CURRICULUM = {
  k: {
    math: ["count-to-10", "addition-within-5"],
    geometry: ["shape-names"],
    spelling: ["cvc-words"],
    reading: ["picture-comprehension"],
  },
  "1": {
    math: ["addition-within-20", "subtraction-within-20"],
    geometry: ["shape-sides"],
    spelling: ["spelling-fill", "sight-words"],
    reading: ["reading-comprehension", "main-idea"],
  },
  "2": {
    math: ["addition-within-100", "subtraction-within-100", "skip-counting"],
    geometry: ["shape-sides", "symmetry"],
    spelling: ["digraphs", "plurals"],
    reading: ["sequence", "character"],
  },
  "3": {
    math: ["multiplication-within-10", "division-basic"],
    geometry: ["perimeter-intro", "angles-intro"],
    spelling: ["prefixes", "suffixes"],
    reading: ["main-idea", "inference"],
  },
  "4": {
    math: ["multi-digit-multiplication", "fractions-intro"],
    geometry: ["area-rectangle", "angle-types"],
    spelling: ["homophones", "compound-words"],
    reading: ["context-clues", "summarize"],
  },
  "5": {
    math: ["fractions-add", "decimals-intro"],
    geometry: ["volume-intro", "coordinate-plane"],
    spelling: ["silent-letters", "syllables"],
    reading: ["theme", "authors-purpose"],
  },
  "6": {
    math: ["ratios", "percentages"],
    geometry: ["area-triangle", "circle-parts"],
    spelling: ["greek-latin-roots", "commonly-confused"],
    reading: ["inference", "compare-contrast"],
  },
};

// Every skill tag the factory knows a fast LOCAL generator for (no model call).
// Anything not in here is generated by the model with a skill-specific prompt.
export const LOCALLY_GENERATED_SKILLS = new Set([
  "addition-within-5",
  "addition-within-20",
  "subtraction-within-20",
  "addition-within-100",
  "subtraction-within-100",
  "shape-names",
  "shape-sides",
]);

export function skillsFor(grade, subject) {
  return (CURRICULUM[grade] && CURRICULUM[grade][subject]) || [];
}

// Build a balanced list of generation targets, at most `count` of them, spread
// across grades and subjects so no single grade/subject dominates a weekly run.
// Each target: { grade, subject, quizType, skill }.
export function generationTargets(count = 50, opts = {}) {
  const grades = opts.grades || GRADES;
  const subjects = opts.subjects || SUBJECTS;
  // Flatten every (grade, subject, skill) combination the map defines.
  const all = [];
  for (const grade of grades) {
    for (const subject of subjects) {
      for (const skill of skillsFor(grade, subject)) {
        all.push({ grade, subject, quizType: SUBJECT_TO_QUIZTYPE[subject] || subject, skill });
      }
    }
  }
  if (!all.length) return [];
  // Round-robin by (grade+subject) bucket so the mix stays even as we fill up to
  // `count`. We cycle skills within each bucket too.
  const buckets = new Map();
  for (const t of all) {
    const k = `${t.grade}|${t.subject}`;
    if (!buckets.has(k)) buckets.set(k, []);
    buckets.get(k).push(t);
  }
  const order = [...buckets.keys()];
  const out = [];
  let i = 0;
  const cursor = new Map(order.map((k) => [k, 0]));
  let safety = count * 4 + order.length;
  while (out.length < count && safety-- > 0) {
    const k = order[i % order.length];
    const list = buckets.get(k);
    const c = cursor.get(k);
    if (c < list.length) {
      out.push(list[c]);
      cursor.set(k, c + 1);
    } else if (list.length) {
      // Bucket exhausted its distinct skills; reuse from the top so a weekly run
      // can still reach the target volume (the factory de-dupes by content).
      out.push(list[c % list.length]);
      cursor.set(k, c + 1);
    }
    i++;
  }
  return out.slice(0, count);
}

export default { GRADES, SUBJECTS, CURRICULUM, SUBJECT_TO_QUIZTYPE, LOCALLY_GENERATED_SKILLS, skillsFor, generationTargets };
